Add propagate-uid-gid option
Add an option, `propagate-uid-gid`, to match the container UID/GID to
the host UID/GID. This avoids littering shared mounts with root-owned
files. The existing `user` option isn't quite flexible enough, as it
requires you to know the name of the user you want to run as, and often
you just want to use whatever UID/GID the host agent happens to be
running as.

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -149,8 +149,17 @@ if [[ -n "${workdir:-}" ]] || [[ "${BUILDKITE_PLUGIN_DOCKER_MOUNT_CHECKOUT:-on}"
 fi
 
 # Support docker run --user
+if [[ -n "${BUILDKITE_PLUGIN_DOCKER_USER:-}" ]] && [[ -n "${BUILDKITE_PLUGIN_DOCKER_PROPAGATE_UID_GID:-}" ]]; then
+  echo "+++ Error: Can't set both user and propagate-uid-gid"
+  exit 1
+fi
+
 if [[ -n "${BUILDKITE_PLUGIN_DOCKER_USER:-}" ]] ; then
   args+=("-u" "${BUILDKITE_PLUGIN_DOCKER_USER:-}")
+fi
+
+if [[ -n "${BUILDKITE_PLUGIN_DOCKER_PROPAGATE_UID_GID:-}" ]] ; then
+  args+=("-u" "$(id -u):$(id -g)")
 fi
 
 # Support docker run --group-add
