Add command logic for copy-checkout

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -111,8 +111,18 @@ fi
 
 workdir=''
 
-if [[ -n "${BUILDKITE_PLUGIN_DOCKER_WORKDIR:-}" ]] || [[ "${BUILDKITE_PLUGIN_DOCKER_MOUNT_CHECKOUT:-on}" =~ ^(true|on|1)$ ]] ; then
+# Set the workdir
+if [[ -n "${BUILDKITE_PLUGIN_DOCKER_WORKDIR:-}" ]] || [[ "${BUILDKITE_PLUGIN_DOCKER_MOUNT_CHECKOUT:-on}" =~ ^(true|on|1)$ ]] || [[ "${BUILDKITE_PLUGIN_DOCKER_COPY_CHECKOUT:-off}" =~ ^(true|on|1)$ ]] ; then
   workdir="${BUILDKITE_PLUGIN_DOCKER_WORKDIR:-$workdir_default}"
+fi
+
+# If copy-checkout, then set mount-checkout to false
+if  [[ "${BUILDKITE_PLUGIN_DOCKER_COPY_CHECKOUT:-off}" =~ ^(true|on|1)$ ]] ; then
+  if [[ "${BUILDKITE_PLUGIN_DOCKER_MOUNT_CHECKOUT:-off}" =~ ^(true|on|1)$ ]] ; then
+    echo "+++ Error: Can't set both copy-checkout and mount-checkout.  Only one can be enabled."
+    exit 1
+  fi
+  BUILDKITE_PLUGIN_DOCKER_MOUNT_CHECKOUT='off'
 fi
 
 # By default, mount $PWD onto $WORKDIR
@@ -408,3 +418,8 @@ echo
 # Don't convert paths on gitbash on windows, as that can mangle user paths and cmd options.
 # See https://github.com/buildkite-plugins/docker-buildkite-plugin/issues/81 for more information.
 ( if is_windows ; then export MSYS_NO_PATHCONV=1; fi && docker run "${args[@]}" )
+
+# Copy files into the workdir if copy-checkout is enabled
+if [[ "${BUILDKITE_PLUGIN_DOCKER_COPY_CHECKOUT:-off}" =~ ^(true|on|1)$ ]] ; then
+    docker copy "$pwd_default" "$container_name":"$workdir"
+fi
