Detect defaults for workdir and shell for windows

diff --git a/hooks/command b/hooks/command
--- a/hooks/command
+++ b/hooks/command
@@ -54,11 +54,15 @@ fi
 
 tty_default='on'
 mount_agent_default='on'
+pwd_default="$PWD"
+workdir_default="/workdir"
 
 # Set operating system specific defaults
 if is_windows ; then
   tty_default=''
   mount_agent_default=''
+  workdir_default="C:\\workdir"
+  pwd_default="$(cmd.exe /C "echo %CD%")"
 elif is_macos ; then
   mount_agent_default=''
 fi
@@ -75,12 +79,12 @@ fi
 args+=("--rm")
 
 if [[ -n "${BUILDKITE_PLUGIN_DOCKER_MOUNTS:-}" && ! "${BUILDKITE_PLUGIN_DOCKER_MOUNTS:-}" =~ ^(true|false)$ ]] ; then
-  echo -n "🚨 The Docker Plugin’s mounts configuration option must be an array or a boolean."
+  echo "🚨 The Docker Plugin’s mounts configuration option must be an array or a boolean."
   exit 1
 fi
 
 if [[ -n "${BUILDKITE_PLUGIN_DOCKER_VOLUMES:-}" && ! "${BUILDKITE_PLUGIN_DOCKER_VOLUMES:-}" =~ ^(true|false)$ ]] ; then
-  echo -n "🚨 The Docker Plugin’s volumes configuration option must be an array or a boolean."
+  echo "🚨 The Docker Plugin’s volumes configuration option must be an array or a boolean."
   exit 1
 fi
 
@@ -95,12 +99,12 @@ if plugin_read_list_into_result BUILDKITE_PLUGIN_DOCKER_VOLUMES BUILDKITE_PLUGIN
 
 # By default, mount $PWD onto $WORKDIR
 elif [[ "${BUILDKITE_PLUGIN_DOCKER_MOUNTS:-}" != "false  " ]] ; then
-  args+=( "--volume" "$PWD:${BUILDKITE_PLUGIN_DOCKER_WORKDIR:-/workdir}" )
+  args+=( "--volume" "${pwd_default}:${BUILDKITE_PLUGIN_DOCKER_WORKDIR:-$workdir_default}" )
 fi
 
 # Set workdir if one is provided or if mounts is the default
 if [[ -n "${BUILDKITE_PLUGIN_DOCKER_WORKDIR:-}" ]] || [[ -n "$default_volumes" ]]; then
-  args+=("--workdir" "${BUILDKITE_PLUGIN_DOCKER_WORKDIR:-/workdir}")
+  args+=("--workdir" "${BUILDKITE_PLUGIN_DOCKER_WORKDIR:-$workdir_default}")
 fi
 
 # Support docker run --user
@@ -118,9 +122,17 @@ done < <(env | sort)
 # Handle the mount-buildkite-agent option
 if [[ "${BUILDKITE_PLUGIN_DOCKER_MOUNT_BUILDKITE_AGENT:-$mount_agent_default}" =~ ^(true|on|1)$ ]] ; then
   if [[ -z "${BUILDKITE_AGENT_BINARY_PATH:-}" ]] ; then
-    BUILDKITE_AGENT_BINARY_PATH=$(command -v buildkite-agent)
+    if ! command -v buildkite-agent >/dev/null 2>&1 ; then
+      echo -n "+++ 🚨 Failed to find buildkite-agent in PATH to mount into container, "
+      echo "you can disable this behaviour with 'mount-buildkite-agent:false'"
+    else
+      BUILDKITE_AGENT_BINARY_PATH=$(command -v buildkite-agent)
+    fi
   fi
+fi
 
+# Mount buildkite-agent if we have a path for it
+if [[ -n "${BUILDKITE_AGENT_BINARY_PATH:-}" ]] ; then
   args+=(
     "--env" "BUILDKITE_JOB_ID"
     "--env" "BUILDKITE_BUILD_ID"
@@ -199,7 +211,11 @@ args+=("${BUILDKITE_PLUGIN_DOCKER_IMAGE}")
 
 # Set a default shell if one is needed
 if [[ -z $shell_disabled ]] && [[ ${#shell[@]} -eq 0 ]] ; then
-  shell=("/bin/sh" "-e" "-c")
+  if is_windows ; then
+    shell=("CMD.EXE" "/c")
+  else
+    shell=("/bin/sh" "-e" "-c")
+  fi
 fi
 
 command=()
